version: "3.1"

services:
  ips:
    container_name: dsar-image-processing-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
      - "5000:5000"
    env_file: '.env'

